# Generated by Django 5.1.3 on 2024-12-11 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_userprofile_adress_alter_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='adress',
            new_name='address',
        ),
    ]
