# Generated by Django 5.1.3 on 2024-12-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_adress_userprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='game_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
