# Generated by Django 5.1.3 on 2024-12-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_userprofile_game_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groundname', models.CharField(max_length=100)),
                ('gamename', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('slots', models.IntegerField()),
                ('image', models.FileField(upload_to='static\\GroundImages')),
                ('status', models.CharField(default='Available', max_length=100)),
            ],
            options={
                'db_table': 'Grounds',
            },
        ),
    ]
