# Generated by Django 5.1.7 on 2025-03-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_groundslotsmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groundslotsmodel',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='groundslotsmodel',
            name='start_time',
        ),
        migrations.AddField(
            model_name='groundslotsmodel',
            name='slotTimings',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
