# Generated by Django 5.1.7 on 2025-03-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_groundslotsmodel_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groundslotsmodel',
            name='slotTimings',
        ),
        migrations.AddField(
            model_name='groundslotsmodel',
            name='end_time',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='groundslotsmodel',
            name='start_time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
