# Generated by Django 5.1.7 on 2025-03-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_groundslotsmodel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groundslotsmodel',
            name='gameName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
