# Generated by Django 5.1.7 on 2025-03-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_groundslotsmodel_gamename'),
    ]

    operations = [
        migrations.AddField(
            model_name='groundslotsmodel',
            name='slotPrice',
            field=models.IntegerField(null=True),
        ),
    ]
