# Generated by Django 5.1.7 on 2025-03-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_groundslotsmodel_slotprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='slotPaymentModel',
            fields=[
                ('paymentID', models.AutoField(primary_key=True, serialize=False)),
                ('cardNumber', models.CharField(max_length=100, null=True)),
                ('cardHolderName', models.CharField(max_length=50, null=True)),
                ('groundName', models.CharField(max_length=50, null=True)),
                ('gameName', models.CharField(max_length=50, null=True)),
                ('userEmail', models.EmailField(max_length=254, null=True)),
                ('paid', models.CharField(max_length=50, null=True)),
                ('paymentDate', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
