# Generated by Django 5.1.7 on 2025-03-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_slotpaymentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotpaymentmodel',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
