# Generated by Django 5.1.7 on 2025-03-26 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_slotpaymentmodel_location'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='slotpaymentmodel',
            table='slotPaymentModel',
        ),
    ]
