# Generated by Django 5.1.7 on 2025-03-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_slotpaymentmodel_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='teamModel',
            fields=[
                ('teamID', models.AutoField(primary_key=True, serialize=False)),
                ('teamLeaderName', models.CharField(max_length=50, null=True)),
                ('teamLeaderMail', models.EmailField(max_length=254, null=True)),
                ('team', models.JSONField(default=list)),
                ('groundName', models.CharField(max_length=50, null=True)),
                ('gameName', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'teamModel',
            },
        ),
    ]
