# Generated by Django 5.1.7 on 2025-03-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_teammodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotpaymentmodel',
            name='end_time',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='slotpaymentmodel',
            name='start_time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
