# Generated by Django 5.1.7 on 2025-03-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_slotpaymentmodel_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='userRequestModel',
            fields=[
                ('requestID', models.AutoField(primary_key=True, serialize=False)),
                ('requestReciever', models.EmailField(max_length=254, null=True)),
                ('requestSender', models.EmailField(max_length=254, null=True)),
                ('requestStatus', models.CharField(default='not accepted', max_length=50)),
            ],
            options={
                'db_table': 'userRequestModel',
            },
        ),
    ]
