# Generated by Django 5.1.7 on 2025-03-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_userrequestmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequestmodel',
            name='recieverTeamId',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
