# Generated by Django 5.1.7 on 2025-03-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_userrequestmodel_recieverteamid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequestmodel',
            name='gameName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userrequestmodel',
            name='groundName',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
