# Generated by Django 5.1.7 on 2025-03-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_userrequestmodel_gamename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequestmodel',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
