# Generated by Django 5.1.7 on 2025-03-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_userrequestmodel_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='groundslotsmodel',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
