# Generated by Django 5.2.3 on 2025-06-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_grounds_price_alter_groundslotsmodel_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grounds',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile',
            field=models.URLField(blank=True, null=True),
        ),
    ]
